title: "SaaS Bundle Hub"
description: "Curated SaaS tools for growth hackers."
baseurl:  ""         
url: https://startuptools.nl/    
theme: minima
plugins:
  - jekyll-feed

environment: production

collections:
  social:
    output: true
    permalink: /social/:title
